### ISSUE TITLE
Default compilation

### ISSUE THREAD

**Issue by datazuul** [tagbangers/wallride#58]
hi, after cloning from git, I tried to do a default
mvn clean install in top module "wallride".

Get error:
The project org.wallride:wallride-bootstrap:1.0.0.M7 (/home/ralf/DEV/SOURCES/wallride/wallride-bootstrap/pom.xml) has 1 error
    Unknown packaging: ${packaging.type} @ line 13, column 16

Seems that no profile is set as default... which profile to choose for default? ("jar" or "war")
As it seems to be a spring boot application, "jar" should be default, shouldn't it?

**Comment by bourbonizable** [comment]
@datazuul 
Hi Ralf, thank you for your feedback!

Actually WallRide doesn't have default packaging type. 
If you want to include Tomcat, please set "jar",
```
mvn clean install -P jar
```
 otherwise set "war".
```
mvn clean install -P war
```

And Quick Start might help you out, please refer to the link below as well.
https://github.com/tagbangers/wallride/wiki/Quick-start

We're looking forward to more feedback from you!

**Comment by bourbonizable** [comment]
I'll close this issue now, if you have any questions about packaging profile, please open a new issue!
Thank you.
