### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by bevrard** [tagbangers/wallride#74]
Hi,

I'm trying to configure Google Analytics module.  Could you tell me why we need to define p12, profileId, custom dimension and service account id?

Why these parameters are mandatory? it's not possible to only define the tracking Id?

By the way, Wallride is amazing ;-) I'm using it now in production :).

Thanks!

**Comment by GuillaumeAMM12** [comment]
Hello i'm just discovering wallride, but i need to find extra classes like Article_ etc (note the underscore)
There are used in the project . May be HashMap properties classes ?
Have you find them ? 
Thanks for your help.

**Comment by bevrard** [comment]
You are looking for a classe with underscore?

**Comment by GuillaumeAMM12** [comment]
Yes this class is imported in ArticleSpecifications.java , Category_ in CategorySpecifications.java ..etc
It seem that these class are used in static manner ( ex:
predicates.add(cb.equal(root.get(Article_.drafted), article)); )
i try to replace by Article with modifing attribute visibility but it not functionning...

Thank

**Comment by bourbonizable** [comment]
Hi @bevrard !!!! We apologize the long long silence because of hectic days.. we're still alive 
The reason why we use custom dimension of Google Analytics(and make it mandatory) is that
even if URL of the article get changed we wanted to keep the page count of the article and calculate it as the same page.
However, more than that reason, it'll be simple for counting to be managed by tracking id as you mentioned, we will improve to enable google analytics set in both ways in the near future.

> By the way, Wallride is amazing ;-) I'm using it now in production :).
It's such an honor to be told that! we're going to keep at it :).

**Comment by bevrard** [comment]
Thanks for your answer!  I'll make the change in my dev version.
